# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: settings.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0esettings.proto\x12\rtrap_protocol\"\x89\x01\n\x0bSettingsMsg\x12\x11\n\ttrap_name\x18\x01 \x01(\t\x12\x11\n\twifi_ssid\x18\x02 \x01(\t\x12\x15\n\rwifi_password\x18\x03 \x01(\t\x12\x14\n\x0cwifi_enabled\x18\x04 \x01(\x08\x12\x14\n\x0cmax_sessions\x18\x05 \x01(\x05\x12\x11\n\tmin_score\x18\x06 \x01(\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'settings_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SETTINGSMSG._serialized_start=34
  _SETTINGSMSG._serialized_end=171
# @@protoc_insertion_point(module_scope)
