# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/sessions.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/sessions.proto\"\x1a\n\x07Session\x12\x0f\n\x07session\x18\x01 \x01(\t\"5\n\x0eSessionDetails\x12\x0f\n\x07session\x18\x01 \x01(\t\x12\x12\n\ndetections\x18\x02 \x01(\x05\"\xac\x01\n\tDetection\x12\x0f\n\x07session\x18\x01 \x01(\t\x12\x11\n\tdetection\x18\x02 \x01(\x05\x12\x0f\n\x07\x63reated\x18\x03 \x01(\x03\x12\x0f\n\x07updated\x18\x04 \x01(\x03\x12\r\n\x05score\x18\x05 \x01(\x02\x12\r\n\x05\x63lazz\x18\x06 \x01(\x05\x12\r\n\x05width\x18\x07 \x01(\x05\x12\x0e\n\x06height\x18\x08 \x01(\x05\x12\x12\n\x05image\x18\t \x01(\x0cH\x00\x88\x01\x01\x42\x08\n\x06_imageb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.sessions_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SESSION._serialized_start=24
  _SESSION._serialized_end=50
  _SESSIONDETAILS._serialized_start=52
  _SESSIONDETAILS._serialized_end=105
  _DETECTION._serialized_start=108
  _DETECTION._serialized_end=280
# @@protoc_insertion_point(module_scope)
