# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: picam3.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cpicam3.proto\":\n\x08StateMsg\x12\x1c\n\x04mode\x18\x01 \x01(\x0e\x32\x0e.AutofocusMode\x12\x10\n\x08position\x18\x02 \x01(\x01\"*\n\nSetModeMsg\x12\x1c\n\x04mode\x18\x01 \x01(\x0e\x32\x0e.AutofocusMode\"\"\n\x0eSetPositionMsg\x12\x10\n\x08position\x18\x02 \x01(\x01\"\x0c\n\nTriggerMsg*:\n\rAutofocusMode\x12\n\n\x06manual\x10\x00\x12\x0e\n\ncontinuous\x10\x01\x12\r\n\ttriggered\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'picam3_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AUTOFOCUSMODE._serialized_start=170
  _AUTOFOCUSMODE._serialized_end=228
  _STATEMSG._serialized_start=16
  _STATEMSG._serialized_end=74
  _SETMODEMSG._serialized_start=76
  _SETMODEMSG._serialized_end=118
  _SETPOSITIONMSG._serialized_start=120
  _SETPOSITIONMSG._serialized_end=154
  _TRIGGERMSG._serialized_start=156
  _TRIGGERMSG._serialized_end=168
# @@protoc_insertion_point(module_scope)
